apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yydj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yydj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yydj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yydj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yydj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-usqv-tenant/rhtap-demo-app/hacbs-test-project-yydj@sha256:9bc9438600afc7dababb9e0c36fc6588d5499e965660ca51da49562e9820c310
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
